server:
  # 端口
  port: 8082
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: dhwmylmkvmebfead
    # 发送者邮箱地址
    username: 1145755268@qq.com
    # 端口（不同邮箱端口号不同）官方465用不了！！！
    port: 587

  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: hhh
    # 密码
    password: 111111
    # 服务器地址
    host: 120.77.60.161
    # 端口
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual

  # Redis配置
  redis:
    # 连接超时时间
    timeout: 10000ms
    # Redis服务器地址
    host: 120.77.60.161
    # Redis服务器端口
    port: 6379
    # 选择哪个库，默认0库
    database: 0
    # 密码
    password: 111111
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大连接阻塞等待时间，单位毫秒,默认 -1
        max-wait: 10000ms
        # 最大空闲连接，默认 8
        max-idle: 200
        # 最小空闲连接，默认 0
        min-idle: 5